name: Java CI

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - uses: stCarolas/setup-maven@v4.3
        with:
          maven-version: 3.8.2

      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '19'

      - name: 'java-test'
        timeout-minutes: 45
        run: mvn clean install

      - uses: scacap/action-surefire-report@v1
        if: always()